FROM denoland/deno:alpine
EXPOSE 4416
RUN mkdir /app
RUN chown deno /app
USER deno
WORKDIR /app

COPY tsconfig.json package.json deno.lock ./
COPY src/ src/
RUN deno install --allow-scripts=npm:canvas --frozen --entrypoint src/main.ts
RUN deno cache src/main.ts

ENTRYPOINT ["/tini", "--", "/bin/deno", "run", "--allow-env", "--allow-ffi=/app/node_modules/.deno/", "--allow-net", "--allow-read=/app", "src/main.ts"]
