FROM node:25-slim AS build
USER node
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY tsconfig.json ./
COPY src/ src/
RUN npx tsc

FROM node:25-slim AS server
USER node
WORKDIR /app

COPY --from=build /app/build /app/build
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

EXPOSE 4416
ENTRYPOINT ["node", "build/main.js"]
